/**:
    ros__parameters:
      registration_method: "NDT_OMP" # “NDT”或“GICP”或“NDT_OMP”或“GICP_OMP”
      score_threshold: 2.0 # 分数阈值
      ndt_resolution: 1.0 # NDT分辨率
      ndt_step_size: 0.1 # NDT步长
      ndt_num_threads: 0 # NDT线程数 0为使用最大允许线程数
      transform_epsilon: 0.01 # 变换中的小量用于停止匹配迭代
      voxel_leaf_size: 0.2 # 输入点云的下采样大小
      scan_max_range: 100.0 # 激光最大范围
      scan_min_range: 1.0 # 激光最小范围
      scan_period: 0.1 # 激光周期
      pcd_path: "/home/dovejh/projects/point_lio_ros2/src/point_lio_ros2/point_lio/PCD/test2/scans.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 0.0
      frequency: 0.05 # 计算频率
      use_imu: false # 是否使用九轴IMU进行点云畸变矫正
      enable_debug: true
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: base_footprint # 和point-lio保持一致
      point_topic: "/livox/lidar_PointCloud2"
      odom_topic: "/livox/odometry"
      imu_topic: "/livox/imu"
