/**:
    ros__parameters:
      registration_method: "NDT_OMP" # “NDT”或“GICP”或“NDT_OMP”或“GICP_OMP”
      score_threshold: 2.0 # 分数阈值
      ndt_resolution: 1.0 # NDT分辨率
      ndt_step_size: 0.1 # NDT步长
      ndt_num_threads: 0 # NDT线程数 0为使用最大允许线程数
      transform_epsilon: 0.01 # 变换中的小量用于停止匹配迭代
      voxel_leaf_size: 0.05 # 输入点云的下采样大小
      scan_max_range: 100.0 # 激光最大范围
      scan_min_range: 0.3 # 激光最小范围
      scan_period: 0.1 # 激光周期
      pcd_path: "/home/sentry/auto_sentry2024/src/auto_sentry2024/robot_bring_up/PCD/RMUL/scans.pcd"
      set_initial_pose: true
      initial_pose_x: 5.603888988494873
      initial_pose_y: 2.1097302436828613
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: -0.9935173808175841
      initial_pose_qw: 0.11368031497742864
      # initial_pose_x: 0.0
      # initial_pose_y: 0.0
      # initial_pose_z: 0.0
      # initial_pose_qx: 0.0
      # initial_pose_qy: 0.0
      # initial_pose_qz: 0.0
      # initial_pose_qw: 1
      frequency: 1.0 # 计算频率
      cloud_frequency: 10.0 # 点云频率
      integral_time: 1.0 # 积分时间，单位s，将静止后多长时间内的点云积分用于匹配
      static_time_threshold: 1.0 # 静止时间阈值，静止完成后开始积分，积分完成后开始匹配
      static_range_threshold: 0.1 # 静止范围阈值
      force_relocate_time_threshold: 20.0 # 强制重定位时间阈值
      use_imu: false # 是否使用九轴IMU进行点云畸变矫正
      enable_debug: true
      locate_no_map: false
      global_frame_id: map
      odom_frame_id: odom
      base_frame_id: livox # 和point-lio保持一致
      point_topic: "/livox/lidar_PointCloud2"
      imu_topic: "/livox/imu"
